a= input("enter the marks of student 1:")
b= input("enter the marks of student 2:")
c= input("enter the marks of student 3:")
d= input("enter the marks of student 4:")
e= input("enter the marks of student 5:")
f= input("enter the marks of student 6:")
g= input("enter the marks of student 7:")
lst = [a,b,c,d,e,f,g]
lst.sort()
print(lst)
